console.log("Hello");
console.log("안녕하세요");
var n = 10;
console.log("결과는 %d입니다", n);
console.log("결과는" + n + "입니다");
var msg = "Happy Day";
console.log("메시지: " + msg + "입니당");
console.log("메시지: %s", msg);
var j = { name: "주하랑" };
console.log("json출력: %j", j);
